# Generated by Django 3.0.7 on 2021-09-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210902_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='Interest',
            new_name='interest',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='dp'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
