# Generated by Django 3.0.7 on 2021-09-02 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210902_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images2', models.ImageField(blank=True, null=True, upload_to='')),
                ('proimage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.User_Profile')),
            ],
        ),
    ]
