# Generated by Django 3.0.7 on 2021-09-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='dp'),
        ),
    ]
