# Generated by Django 3.0.7 on 2021-09-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210905_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_images',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='dp'),
        ),
    ]
