# Generated by Django 3.0.7 on 2021-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210905_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
