# Generated by Django 3.0.7 on 2021-09-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210913_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
