# Generated by Django 3.0.7 on 2021-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210913_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='dp',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
